### ISSUE TITLE
Lodash dependency

### ISSUE THREAD

**Issue by jantimon** [emaphp/underscore-template-loader#14]
Please please add the lodash dependency (at least as peerDependency). Otherwise I can't use this loader for the html-webpack-plugin as it fails without lodash.

Lodash is a clear dependency of this module - as it does not run without it.

How do other loaders handle it?

* https://github.com/okonet/ejs-loader/blob/master/package.json#L26
* https://github.com/shama/stylus-loader/blob/master/package.json#L27
* https://github.com/babel/babel-loader/blob/master/package.json#L15
* https://github.com/jtangelder/sass-loader/blob/master/package.json#L30
* https://github.com/webpack/less-loader/blob/master/package.json#L11
* https://github.com/webpack/jade-loader/blob/master/package.json#L10

**Comment by emaphp** [comment]
This module can run both with underscore and lodash. I think this is a great example of why it's necessary for the lodash community to fork this project and add the changes they believe necessary. This module is aimed to underscore users, lodash support was added only because is seemed convenient at the moment. Adding lodash as a peerDependency is out of the question given that they are already obsolete. I understand your frustation, but I think that mantaining a module that can run with different libraries supporting different features will lead to a messy implementation, more issues and less quality overall.
